

# state
NOT_OPENING_STATE = 0
OPENING_STATE = 1
CLAIMABLE_STATE = 2
EMPTY_STATE = 3

NOT_OPENING_STATE_STR = 'NOT OPENING'
OPENING_STATE_STR = 'OPENING'
CLAIMABLE_STATE_STR = 'CLAIMABLE'
EMPTY_STATE_STR = 'EMPTY'


# item type in chest
# card
OWL_CARD = 0
CROW_CARD = 1
FROG_CARD = 2
BUNNY_CARD = 3
POLAR_CARD = 4
GOAT_CARD = 5
SNAKE_CARD = 6
FIRE_CARD = 7
SNOW_CARD = 8
TRAP_CARD = 9
# gold
GOLD_TYPE = 11
